# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20170303_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeevent',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='compositeevent',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='compositeevent',
            name='visiting_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_events', to='backoffice.VisitingDay'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(upload_to='coupon_images/'),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='visiting_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_events', to='backoffice.VisitingDay'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='composite_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='backoffice.CompositeEvent'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='start',
            field=models.TimeField(),
        ),
    ]
