# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_subevent_visiting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeevent',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='compositeevent',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='coordinator',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standaloneevent',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='coordinator',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visitingday',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
