# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20170419_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositeevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standaloneevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitingday',
            name='id',
        ),
        migrations.AddField(
            model_name='compositeevent',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='standaloneevent',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subevent',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='visitingday',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
