# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_auto_20170526_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositeevent',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='standaloneevent',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='subevent',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='visitingday',
            name='uid',
        ),
        migrations.AddField(
            model_name='compositeevent',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standaloneevent',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subevent',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitingday',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
